const extensionToTypeMap = {
    js: "javascript",
    jsx: "jsx",
    ts: "typescript",
    tsx: "typescript",
    html: "html",
    css: "css",
    scss: "scss",
    sass: "sass",
    less: "less",
    json: "json",
    md: "markdown",
    mdx: "markdown",
    txt: "plaintext",
    py: "python",
    java: "java",
    c: "c",
    cpp: "cpp",
    h: "c",
    cs: "csharp",
    go: "go",
    rb: "ruby",
    php: "php",
    rs: "rust",
    swift: "swift",
    kt: "kotlin",
    yaml: "yaml",
    yml: "yaml",
    png: "plaintext",
    jpg: "plaintext",
    jpeg: "plaintext",
    gif: "plaintext",
    svg: "xml",
    ico: "plaintext",
    env: "plaintext",
    lock: "plaintext",
    sh: "shell",
    bash: "shell",
    Dockerfile: "dockerfile",
    Makefile: "makefile",
    gradle: "gradle",
    gitignore: "plaintext",
    nix: "nix",
    toml: "toml",
    coffee: "coffeescript",
    vue: "vue",
    svelte: "svelte",
    r: "r",
};


export const extensionToFileType = (extension)=>{
    if(!extension) return undefined;
    return extensionToTypeMap[extension]
}